pipeline {
    agent any
    stages {
        stage('Build') {
            steps {
                sh'echo Build stage'
            }
        }
        stage('Test') {
            steps {
                sh'echo Testing stage'
            }
        }
        stage('Package') {
            steps {
                sh'echo Packaging stage'
            }
        }
        stage('Deploy') {
            steps {
                sh'echo Deployment stage'
            }
        }
        stage('Clean Up') {
            steps {
                sh'echo Clean up stage'
            }
        }
    }
}